version: 0.2
env:
  secrets-manager:
    DOCKERHUB_USERNAME: dockerhub-username-secret
    DOCKERHUB_PASSWORD: dockerhub-password-secret
phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 183829413334.dkr.ecr.ap-southeast-1.amazonaws.com
      - REPOSITORY_URI=183829413334.dkr.ecr.ap-southeast-1.amazonaws.com/ws-frontend
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ws-frontend -f ./testpayment6.0/Dockerfile ./testpayment6.0
      - docker tag ws-frontend:latest $REPOSITORY_URI:latest
      - docker tag ws-frontend:latest $REPOSITORY_URI:$COMMIT_HASH

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$COMMIT_HASH
      - echo Build completed on `date`

      - echo Writing imageDetail.json file...
      - printf '{"imageUri":"%s", "BASE_SERVICE":"frontend-service", "rule_arn":""}' $REPOSITORY_URI:$COMMIT_HASH > imageDetail.json
      - cat imageDetail.json

artifacts:
  files:
    - imageDetail.json
